### ISSUE TITLE
[scaffolding-chef-infra] Primary policyfile lockfile being deleted when `include_policy`

### ISSUE THREAD

**Issue by echohack** [chef/effortless#41]
Originally from `habitat-sh/core-plans` by @qubitrenegade 

Hello,

I am having an issue with the `scaffolding-chef` scaffolding, where it appears to be deleting the `base.lockfile.json` when including the `base` policy from another policyfile.

I've created a [demo repo](https://github.com/qubitrenegade/habichef_demo).  The branch `2019-04-28-pt1-multiple-policy-files` has been created with these changes.

I have a fairly standard [plan.sh](https://github.com/qubitrenegade/habichef_demo/blob/2019-04-28-pt1-multiple-policy-files/habitat/plan.sh) file.

And my policy file is:

```
# habichef_demo/policyfiles/us-east-1.rb
name 'us-east-1'
include_policy 'base', path: '.'
default['resolver']['domain'] = 'us-east-1.qubitrenegade.com'
```

When running a build, this fails with:

```
[2][default:/src:0]# CHEF_POLICYFILE=us-east-1 build
... snip ...
Building policy us-east-1
Error: Failed to generate Policyfile.lock
Reason: (ChefDK::LocalPolicyfileLockNotFound) The provided path ./base.lock.json does not exist.
```

If I build it first with:

```
[1][default:/src:0]# build
... snip ...

  habichef_demo-base: Installed Path: /hab/pkgs/qbrd/habichef_demo-base/0.1.0/20190428185221
   habichef_demo-base: Artifact: /src/results/qbrd-habichef_demo-base-0.1.0-20190428185221-x86_64-linux.hart
   habichef_demo-base: Build Report: /src/results/last_build.env
   habichef_demo-base: SHA256 Checksum: 4a126ec5c47dba1643ef767c7ccc02acd36ea780d2f88110db9c964c4598c2b9
   habichef_demo-base: Blake2b Checksum: 7fc45fcf07bebe57f90301c0c83df6700f772fc8925ec0162b1efbfa85b89b6a
   habichef_demo-base:
   habichef_demo-base: I love it when a plan.sh comes together.
   habichef_demo-base:
   habichef_demo-base: Build time: 0m5s
[2][default:/src:0]#
```

It creates a `base.lockfile.json`, but running `CHEF_POLICYFILE=us-east-1 build` again fails with the same error.

This appears to be the result of PR #2515, [L99](https://github.com/habitat-sh/core-plans/blame/932bfaae647d3bd9dde892158b7077b1d19888fc/scaffolding-chef/lib/scaffolding.sh#L99)

```
 rm -f "${scaffold_policyfiles_path}"/*.lock.json
```

Thanks
- QBRD
